/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.areen.jlib.test;

import java.awt.CardLayout;

/**
 *
 * @author Dejan
 */
public class JlibTestFrame extends javax.swing.JFrame {
    BrowserTestPanel browserTestPanel;
    
    /**
     * Creates new form JlibTestFrame
     */
    public JlibTestFrame() {
        initComponents();
        
        browserTestPanel = new BrowserTestPanel();
        contentPanel.add(browserTestPanel, "browser_test");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigatorButtonGroup = new javax.swing.ButtonGroup();
        topPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        mainSplitPane = new javax.swing.JSplitPane();
        navigatorPanel = new javax.swing.JPanel();
        browserButton = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        headerLabel.setText("JLib Tests");
        topPanel.add(headerLabel);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bottomPanel.add(jButton1);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        navigatorPanel.setLayout(new javax.swing.BoxLayout(navigatorPanel, javax.swing.BoxLayout.Y_AXIS));

        navigatorButtonGroup.add(browserButton);
        browserButton.setText("Browser test");
        browserButton.setMaximumSize(new java.awt.Dimension(640, 25));
        browserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browserButtonActionPerformed(evt);
            }
        });
        navigatorPanel.add(browserButton);

        navigatorButtonGroup.add(jToggleButton2);
        jToggleButton2.setText("jToggleButton2");
        jToggleButton2.setMaximumSize(new java.awt.Dimension(640, 25));
        navigatorPanel.add(jToggleButton2);

        mainSplitPane.setLeftComponent(navigatorPanel);

        contentPanel.setLayout(new java.awt.CardLayout());
        mainSplitPane.setRightComponent(contentPanel);

        getContentPane().add(mainSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browserButtonActionPerformed
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "browser_test");
    }//GEN-LAST:event_browserButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JlibTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JlibTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JlibTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JlibTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JlibTestFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JToggleButton browserButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.ButtonGroup navigatorButtonGroup;
    private javax.swing.JPanel navigatorPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
