/**
 * Project: jlib
 * Version: $Id$
 * License: SPL
 * 
 * Authors (in chronological order):
 *   Dejan Lekic - http://dejan.lekic.org
 * Contributors (in chronological order):
 *   -
 */

package com.areen.jlib.test;

import com.areen.jlib.test.panels.BrowserTestPanel;
import com.areen.jlib.test.panels.ImageLoaderPanel;
import com.areen.jlib.test.panels.JXButtonPanel;
import com.areen.jlib.test.panels.VerticalLayoutPanel;
import java.awt.CardLayout;

/**
 * This class is a beginning of JLib's new (manual) testing frame which will be used for all sorts of manual
 * tests.
 * 
 * @author Dejan
 */
public class JlibTestFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form JlibTestFrame
     */
    public JlibTestFrame() {
        initComponents();
        
        contentPanel.add(new BrowserTestPanel(), "browser_test");
        contentPanel.add(new ImageLoaderPanel(), "image_loader_panel");
        contentPanel.add(new JXButtonPanel(), "jxbutton_panel");
        contentPanel.add(new VerticalLayoutPanel(), "vertical_layout_panel");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigatorButtonGroup = new javax.swing.ButtonGroup();
        topPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        mainSplitPane = new javax.swing.JSplitPane();
        navigatorPanel = new javax.swing.JPanel();
        browserButton = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        verticalLayoutButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        topPanel.setBackground(new java.awt.Color(204, 204, 0));
        topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        headerLabel.setText("JLib Tests");
        topPanel.add(headerLabel);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setBackground(new java.awt.Color(51, 204, 0));
        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bottomPanel.add(jButton1);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        navigatorPanel.setLayout(new javax.swing.BoxLayout(navigatorPanel, javax.swing.BoxLayout.Y_AXIS));

        navigatorButtonGroup.add(browserButton);
        browserButton.setText("Browser test");
        browserButton.setMaximumSize(new java.awt.Dimension(640, 25));
        browserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browserButtonActionPerformed(evt);
            }
        });
        navigatorPanel.add(browserButton);

        navigatorButtonGroup.add(jToggleButton2);
        jToggleButton2.setText("ImageLoader test");
        jToggleButton2.setMaximumSize(new java.awt.Dimension(640, 25));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        navigatorPanel.add(jToggleButton2);

        jButton2.setText("JXButton with painters");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        navigatorPanel.add(jButton2);

        verticalLayoutButton.setText("VerticalLayout");
        verticalLayoutButton.setMaximumSize(new java.awt.Dimension(159, 25));
        verticalLayoutButton.setMinimumSize(new java.awt.Dimension(159, 25));
        verticalLayoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalLayoutButtonActionPerformed(evt);
            }
        });
        navigatorPanel.add(verticalLayoutButton);

        mainSplitPane.setLeftComponent(navigatorPanel);

        contentPanel.setLayout(new java.awt.CardLayout());
        mainSplitPane.setRightComponent(contentPanel);

        getContentPane().add(mainSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browserButtonActionPerformed
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "browser_test");
    }//GEN-LAST:event_browserButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "image_loader_panel");
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "jxbutton_panel");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void verticalLayoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalLayoutButtonActionPerformed
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "vertical_layout_panel");
    }//GEN-LAST:event_verticalLayoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JlibTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JlibTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JlibTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JlibTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JlibTestFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JToggleButton browserButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.ButtonGroup navigatorButtonGroup;
    private javax.swing.JPanel navigatorPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton verticalLayoutButton;
    // End of variables declaration//GEN-END:variables
}

// $Id$
