/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.areen.jlib.test;

import com.areen.jlib.gui.TextComponentPopUp;

/**
 *
 * @author Matthew
 */
public class SpellCheckerPanel extends javax.swing.JPanel {

    /**
     * Creates new form SpellCheckerPanel
     */
    public SpellCheckerPanel() {
        initComponents();
        installSpellChecker();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        textField.setText("Some text here to spel czek");
        textField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textFieldMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                textFieldMouseReleased(evt);
            }
        });
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldMouseClicked
        if (evt.isPopupTrigger()) {
          new TextComponentPopUp().show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_textFieldMouseClicked

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed

    }//GEN-LAST:event_textFieldActionPerformed

    private void textFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldMousePressed
     if (evt.isPopupTrigger()) {
          new TextComponentPopUp().show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_textFieldMousePressed

    private void textFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldMouseReleased
       if (evt.isPopupTrigger()) {
          new TextComponentPopUp().show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_textFieldMouseReleased

    private void installSpellChecker() {
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
