/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.areen.jlib.test.panels;

import java.awt.Color;
import java.awt.Dimension;
import org.jdesktop.swingx.JXButton;
import org.jdesktop.swingx.JXPanel;
import org.jdesktop.swingx.painter.CapsulePainter;
import org.jdesktop.swingx.painter.PinstripePainter;

/**
 *
 * @author Dejan
 */
public class JXButtonPanel extends javax.swing.JPanel {

    /**
     * Creates new form JXButtonPanel
     */
    public JXButtonPanel() {
        initComponents();
        
        JXButton b = new JXButton("Execute");
        final CapsulePainter cpainter = new CapsulePainter();
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cpainter.setFillPaint(Color.GREEN);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cpainter.setFillPaint(Color.LIGHT_GRAY);
            }
        });
        cpainter.setFillPaint(Color.LIGHT_GRAY);
        b.setBackgroundPainter(cpainter);
        
        
        JXPanel jxpanel = new JXPanel();
        jxpanel.setPreferredSize(new Dimension(200, 200));
        PinstripePainter pp = new PinstripePainter(45.0);
        jxpanel.setBackgroundPainter(pp);
        jxpanel.add(b);
        add(jxpanel);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
