/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.areen.jlib.test.panels;

import com.areen.jlib.gui.layout.VerticalLayout;
import javax.swing.JButton;

/**
 *
 * @author Dejan
 */
public class VerticalLayoutPanel extends javax.swing.JPanel {

    /**
     * Creates new form VerticalLayoutPanel
     */
    public VerticalLayoutPanel() {
        initComponents();
        setLayout(new VerticalLayout(2, VerticalLayout.LEFT, VerticalLayout.TOP));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
        add(new JButton("Hello there"));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
