/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AreenTablePanel.java
 *
 * Created on 02-Aug-2010, 11:48:30
 */

package jlib.gui.table.areen;

import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jlib.gui.table.areen.filter.FilterPanel;

/**
 *
 * @author dejan
 */
public class AreenTablePanel extends javax.swing.JPanel {

    Map<String,JLabel> map = new HashMap<String,JLabel>();   
    /** Creates new form AreenTablePanel */
    public AreenTablePanel() {
        initComponents();
        filterPanel = null;
        filterPanel = new FilterPanel(defaultTable);
        add(filterPanel, java.awt.BorderLayout.NORTH);
    }
    
    public void setModel(DefaultTableModel dtm){
       ((AreenTable)defaultTable).setTableModel(dtm);
    }

    public void populateCommandComboBox(String[] shortcuts, String[] commands){
       commandComboBox.setModel(new DefaultComboBoxModel(commands));
       populateNavigationPanel(shortcuts, commands);
    }
    
    public void populateNavigationPanel(String[] shortcuts, String[] commands){
       
       for (int i = 2; i < shortcuts.length+2; i++) {
          String st = i+ ordinalNo(i)+ "NavLabel";
          map.put(st,new JLabel());
          JLabel label = map.get(st);
          label.setText("<html><b>" + shortcuts[i-2]+"</b> - " + commands[i-2] +"</html>");
          navigationPanel.add(label);
       }
       /*for (Entry entry : map.entrySet()) {
          System.out.println("Processing object with name: " + entry.getKey());
       }*/
    }
    
    public static String ordinalNo(int value) {
      int hunRem = value % 100;
      int tenRem = value % 10;
      if (hunRem - tenRem == 10) {
         return "th";
      }
      switch (tenRem) {
         case 1:
            return "st";
         case 2:
            return "nd";
         case 3:
            return "rd";
         default:
            return "th";
      }
   }
    
   public void setActionListener(ActionListener al) {
      commandComboBox.addActionListener(al);
   } 

   public JTable getTable(){
      return defaultTable;
   }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      filterPanel = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      bottomPanel = new javax.swing.JPanel();
      commandPanel = new javax.swing.JPanel();
      commandComboBox = new javax.swing.JComboBox();
      commandButton = new javax.swing.JButton();
      navigationPanel = new javax.swing.JPanel();
      firstNavLabel = new javax.swing.JLabel();
      tableStatusPanel = new javax.swing.JPanel();
      tableStatusLabel = new javax.swing.JLabel();
      areenTableScrollPane = new javax.swing.JScrollPane();
      defaultTable = new AreenTable();

      setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
      setLayout(new java.awt.BorderLayout());

      jLabel1.setText("jLabel1");

      javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
      filterPanel.setLayout(filterPanelLayout);
      filterPanelLayout.setHorizontalGroup(
         filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 775, Short.MAX_VALUE)
         .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
               .addGap(0, 370, Short.MAX_VALUE)
               .addComponent(jLabel1)
               .addGap(0, 371, Short.MAX_VALUE)))
      );
      filterPanelLayout.setVerticalGroup(
         filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 16, Short.MAX_VALUE)
         .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
               .addGap(0, 1, Short.MAX_VALUE)
               .addComponent(jLabel1)
               .addGap(0, 1, Short.MAX_VALUE)))
      );

      add(filterPanel, java.awt.BorderLayout.NORTH);

      bottomPanel.setLayout(new java.awt.BorderLayout());

      commandPanel.setLayout(new java.awt.BorderLayout());

      commandComboBox.setEditable(true);
      commandComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      commandPanel.add(commandComboBox, java.awt.BorderLayout.CENTER);

      commandButton.setText("Go!");
      commandPanel.add(commandButton, java.awt.BorderLayout.LINE_END);

      bottomPanel.add(commandPanel, java.awt.BorderLayout.NORTH);

      navigationPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

      firstNavLabel.setText("<html><b>F1</b> - Help</html>");
      navigationPanel.add(firstNavLabel);

      bottomPanel.add(navigationPanel, java.awt.BorderLayout.CENTER);

      tableStatusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
      tableStatusPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

      tableStatusLabel.setText("...");
      tableStatusPanel.add(tableStatusLabel);

      bottomPanel.add(tableStatusPanel, java.awt.BorderLayout.SOUTH);

      add(bottomPanel, java.awt.BorderLayout.PAGE_END);

      areenTableScrollPane.setBorder(null);

      defaultTable.setFont(defaultTable.getFont());
      defaultTable.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      areenTableScrollPane.setViewportView(defaultTable);

      add(areenTableScrollPane, java.awt.BorderLayout.CENTER);
   }// </editor-fold>//GEN-END:initComponents

    
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JScrollPane areenTableScrollPane;
   private javax.swing.JPanel bottomPanel;
   private javax.swing.JButton commandButton;
   private javax.swing.JComboBox commandComboBox;
   private javax.swing.JPanel commandPanel;
   private javax.swing.JTable defaultTable;
   private javax.swing.JPanel filterPanel;
   private javax.swing.JLabel firstNavLabel;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel navigationPanel;
   private javax.swing.JLabel tableStatusLabel;
   private javax.swing.JPanel tableStatusPanel;
   // End of variables declaration//GEN-END:variables

}
